### ISSUE TITLE
Vulnerability: No symlink checking to prevent escape from working directory

### ISSUE THREAD

**Issue by ProfessorDey** [tauoverpi/zangle#4]
Adding to the issues faced in #1 I realised that the path needs to be fully evaluated after the base 'absolute path' and '..' checks to compensate for the existance of symlinking. A symlink that leaves the working directory would be yet another way of accessing parts of the file system that it shouldn't.

This issue is more complex due to how symlinks differ significantly across platforms and filesystems, and whether it is a hard or soft symlink, but it is still a crucial factor for security purposes. The simplest solution would be resolving each file path completely and comparing the absolute path with the working directory, but I am not personally familiar with the way that is done to account for symlinking.

As long as the start of absolute path to the file starts with the absolute path of the working directory, the operations with fixes from #3 should be sufficient to protect against malicious or unintentional modification of files outside of the working directory, though a default behaviour of refusing to overwrite existing files would be advisable as a clean or diff command can always be provided as well.

**Comment by tauoverpi** [comment]
For symlinks, zangle could check the file type and throw an error unless `--follow-symlinks` has been specified and for hardlinks `--allow-hardlink-writes` with the same behaviour of throwing an error by default would work.

Any thoughts?

***

A note for now on the `diff` command,

running `{ zangle ls file.md; find src lib -type f; } | sort | uniq -d` will give all existing files which would be overwritten by zangle as a workaround for now which can be combined with `diff` and `zangle call --file=example.zig` to see the difference before a write.

I'll need to think about this one a bit. Feel free to open it as a feature request.

**Comment by tauoverpi** [comment]
I've decided to disallow absolute paths and if someone has the ability to create symlinks then it's out of scope for zangle to handle it. Can discuss this one further on matrix but for now I'm closing it as I don't see what I can really do here.
